version: "3"

services:
  db_product:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: product_service
    volumes:
      - db-product-data:/var/lib/postgresql/data

  db_customer:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=customer_service
    volumes:
      - db-customer-data:/var/lib/mysql

  db_transaction:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=transaction_service
    volumes:
      - db-transaction-data:/var/lib/mysql

  discovery:
    image: residwi/simple-microservices-demo-service-discovery:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    restart: unless-stopped

  config-server:
    image: residwi/simple-microservices-demo-config-server:0.0.1-SNAPSHOT
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery

  api-gateway:
    image: residwi/simple-microservices-demo-api-gateway:0.0.1-SNAPSHOT
    restart: on-failure
    ports:
      - 8888:8888
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery

  product:
    image: residwi/simple-microservices-demo-product:0.0.1-SNAPSHOT
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DDATABASE_URL=jdbc:postgresql://db_product:5432/product_service?serverTimezone=UTC
        -DDATABASE_USERNAME=postgres
        -DDATABASE_PASSWORD=secret
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - db_product

  transaction:
    image: residwi/simple-microservices-demo-transaction:0.0.1-SNAPSHOT
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DDATABASE_URL=jdbc:mysql://db_transaction:3306/transaction_service?serverTimezone=UTC
        -DDATABASE_USERNAME=root
        -DDATABASE_PASSWORD=root
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - db_transaction

  customer:
    image: residwi/simple-microservices-demo-customer:0.0.1-SNAPSHOT
    restart: on-failure
    environment:
      - JAVA_OPTS=
        -DDATABASE_URL=jdbc:mysql://db_customer:3306/customer_service?serverTimezone=UTC
        -DDATABASE_USERNAME=root
        -DDATABASE_PASSWORD=root
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - db_customer

volumes:
  db-product-data:
    driver: local
  db-transaction-data:
    driver: local
  db-customer-data:
    driver: local